/* The following code was generated by JFlex 1.4.3 on 20/06/20 10:05 PM */

package Ventanas;
import java_cup.runtime.Symbol;

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 20/06/20 10:05 PM from the specification file
 * <tt>C:/Users/cesar/Desktop/CompiladorBP/BraillePrint/src/Ventanas/LexerCup.flex</tt>
 */
class LexerCup implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = {
     0,  0,  0,  0,  0,  0,  0,  0,  0,  5,  9,  0,  0,  5,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     5, 12, 10,  8,  0,  0, 11,  0, 33, 34,  6,  4, 39, 32, 39,  7, 
     2,  2,  2,  2,  2,  2,  2,  2,  2,  2,  0, 31, 13, 14, 13,  0, 
     0, 28,  1, 48,  1, 22, 27,  1,  1, 49,  1,  1, 29,  1,  1,  1, 
     1,  1, 20, 30, 19, 21, 51,  1,  1,  1,  1, 37,  0, 38,  0,  3, 
     0, 24,  1, 43, 46, 18, 23, 47,  1, 44,  1,  1, 25, 45, 40, 41, 
    50,  1, 16, 26, 15, 17, 42,  1,  1,  1,  1, 35,  5, 36,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  1,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0,  0, 
     0,  1,  0,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  1,  0,  0, 
     0,  1,  0,  1,  0,  0,  0,  0,  0,  0,  1,  0,  0,  0,  0,  0
  };

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\1\2\1\3\1\4\1\5\1\6\1\7"+
    "\1\1\1\10\2\11\1\12\1\13\6\2\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\1\4\2"+
    "\1\24\1\25\1\3\1\26\2\0\1\5\1\0\1\27"+
    "\1\12\6\2\1\30\11\2\1\24\1\0\20\2\1\0"+
    "\1\5\1\31\1\2\1\32\1\2\1\33\5\2\1\34"+
    "\4\2\1\35\6\2\1\36\1\37\3\2\1\40\5\2"+
    "\1\41\5\2\1\42\1\2\1\43\1\2\1\44\1\2"+
    "\1\45\3\2\1\46";

  private static int [] zzUnpackAction() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\64\0\150\0\234\0\320\0\u0104\0\u0138\0\u016c"+
    "\0\u01a0\0\u01d4\0\64\0\u0208\0\u0208\0\u023c\0\u0270\0\u02a4"+
    "\0\u02d8\0\u030c\0\u0340\0\u0374\0\64\0\u03a8\0\64\0\64"+
    "\0\64\0\64\0\64\0\64\0\u03dc\0\u0410\0\u0444\0\u0478"+
    "\0\u04ac\0\u04e0\0\u0514\0\u0548\0\64\0\u03dc\0\u057c\0\u05b0"+
    "\0\u01d4\0\u01d4\0\64\0\u05e4\0\u0618\0\u064c\0\u0680\0\u06b4"+
    "\0\u06e8\0\u071c\0\u0750\0\u0784\0\u07b8\0\u07ec\0\u0820\0\u0854"+
    "\0\u0888\0\u08bc\0\u08f0\0\u0924\0\u0958\0\u098c\0\u09c0\0\u09f4"+
    "\0\u0a28\0\u0a5c\0\u0a90\0\u0ac4\0\u0af8\0\u0b2c\0\u0b60\0\u0b94"+
    "\0\u0bc8\0\u0bfc\0\u0c30\0\u0c64\0\u0c98\0\u0ccc\0\64\0\u04ac"+
    "\0\u0d00\0\u04ac\0\u0d34\0\u04ac\0\u0d68\0\u0d9c\0\u0dd0\0\u0e04"+
    "\0\u0e38\0\u04ac\0\u0e6c\0\u0ea0\0\u0ed4\0\u0f08\0\u04ac\0\u0f3c"+
    "\0\u0f70\0\u0fa4\0\u0fd8\0\u100c\0\u1040\0\u04ac\0\u04ac\0\u1074"+
    "\0\u10a8\0\u10dc\0\u04ac\0\u1110\0\u1144\0\u1178\0\u11ac\0\u11e0"+
    "\0\u04ac\0\u1214\0\u1248\0\u127c\0\u12b0\0\u12e4\0\u04ac\0\u1318"+
    "\0\u04ac\0\u134c\0\u04ac\0\u1380\0\u04ac\0\u13b4\0\u13e8\0\u141c"+
    "\0\u04ac";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\1\4\1\2\1\5\1\6\1\7\1\10"+
    "\1\11\1\6\1\12\1\13\1\14\1\15\1\16\1\17"+
    "\2\3\1\20\1\21\3\3\1\22\2\3\1\23\1\24"+
    "\3\3\1\25\1\26\1\27\1\30\1\31\1\32\1\33"+
    "\1\34\1\35\2\3\1\36\1\37\2\3\1\40\5\3"+
    "\65\0\2\41\14\0\20\41\11\0\14\41\1\0\1\42"+
    "\1\4\14\0\20\42\10\0\1\43\14\42\2\0\1\44"+
    "\13\0\1\45\30\0\1\46\21\0\1\6\3\0\1\6"+
    "\70\0\1\45\53\0\1\47\7\0\1\45\55\0\1\50"+
    "\53\0\11\51\1\0\1\52\51\51\16\0\1\53\51\0"+
    "\1\45\1\0\2\45\6\0\1\53\21\0\1\45\24\0"+
    "\2\41\14\0\1\41\1\54\16\41\11\0\14\41\1\0"+
    "\2\41\14\0\20\41\11\0\1\55\13\41\1\0\2\41"+
    "\14\0\5\41\1\56\12\41\11\0\14\41\1\0\2\41"+
    "\14\0\11\41\1\57\1\60\5\41\11\0\14\41\1\0"+
    "\2\41\14\0\3\41\1\61\14\41\11\0\4\41\1\62"+
    "\7\41\1\0\2\41\14\0\15\41\1\63\1\64\1\41"+
    "\11\0\10\41\1\65\1\66\1\41\1\67\2\0\1\43"+
    "\13\0\1\45\30\0\1\46\16\0\1\43\44\0\1\46"+
    "\15\0\2\41\14\0\11\41\1\70\6\41\11\0\14\41"+
    "\1\0\2\41\14\0\11\41\1\71\6\41\11\0\4\41"+
    "\1\72\7\41\1\0\2\41\14\0\3\41\1\73\14\41"+
    "\11\0\14\41\1\0\2\41\1\3\13\0\20\41\11\0"+
    "\14\41\1\0\2\74\14\0\20\74\11\0\14\74\2\0"+
    "\1\43\44\0\1\43\16\0\1\44\44\0\1\43\14\0"+
    "\6\47\1\75\55\47\11\50\1\0\52\50\1\0\2\41"+
    "\1\3\13\0\2\41\1\76\15\41\11\0\14\41\1\0"+
    "\2\41\1\3\13\0\1\77\17\41\11\0\14\41\1\0"+
    "\2\41\1\3\13\0\6\41\1\100\11\41\11\0\14\41"+
    "\1\0\2\41\1\3\13\0\12\41\1\101\5\41\11\0"+
    "\14\41\1\0\2\41\1\3\13\0\20\41\11\0\1\41"+
    "\1\102\12\41\1\0\2\41\1\3\13\0\12\41\1\103"+
    "\5\41\11\0\14\41\1\0\2\41\1\3\13\0\20\41"+
    "\11\0\1\104\13\41\1\0\2\41\1\3\13\0\16\41"+
    "\1\105\1\41\11\0\14\41\1\0\2\41\1\3\13\0"+
    "\20\41\11\0\1\41\1\106\12\41\1\0\2\41\1\3"+
    "\13\0\20\41\11\0\1\41\1\107\12\41\1\0\2\41"+
    "\1\3\13\0\20\41\11\0\5\41\1\110\6\41\1\0"+
    "\2\41\1\3\13\0\11\41\1\111\6\41\11\0\14\41"+
    "\1\0\2\41\1\3\13\0\1\41\1\112\16\41\11\0"+
    "\14\41\1\0\2\41\1\3\13\0\13\41\1\113\4\41"+
    "\11\0\14\41\1\0\2\41\1\3\13\0\20\41\11\0"+
    "\3\41\1\114\10\41\1\0\2\41\1\3\13\0\20\41"+
    "\11\0\3\41\1\115\10\41\1\0\2\74\1\42\13\0"+
    "\20\74\11\0\14\74\6\47\1\116\1\117\54\47\1\0"+
    "\2\41\1\3\13\0\3\41\1\120\14\41\11\0\14\41"+
    "\1\0\2\41\1\3\13\0\3\41\1\121\14\41\11\0"+
    "\14\41\1\0\2\41\1\3\13\0\7\41\1\120\10\41"+
    "\11\0\14\41\1\0\2\41\1\3\13\0\13\41\1\76"+
    "\4\41\11\0\14\41\1\0\2\41\1\3\13\0\1\122"+
    "\17\41\11\0\14\41\1\0\2\41\1\3\13\0\3\41"+
    "\1\123\14\41\11\0\14\41\1\0\2\41\1\3\13\0"+
    "\20\41\11\0\1\41\1\124\12\41\1\0\2\41\1\3"+
    "\13\0\17\41\1\100\11\0\14\41\1\0\2\41\1\3"+
    "\13\0\20\41\11\0\1\125\13\41\1\0\2\41\1\3"+
    "\13\0\20\41\11\0\1\126\13\41\1\0\2\41\1\3"+
    "\13\0\20\41\11\0\12\41\1\127\1\41\1\0\2\41"+
    "\1\3\13\0\12\41\1\130\5\41\11\0\14\41\1\0"+
    "\2\41\1\3\13\0\20\41\11\0\3\41\1\131\10\41"+
    "\1\0\2\41\1\3\13\0\20\41\11\0\1\41\1\132"+
    "\12\41\1\0\2\41\1\3\13\0\12\41\1\133\5\41"+
    "\11\0\14\41\1\0\2\41\1\3\13\0\12\41\1\134"+
    "\5\41\11\0\14\41\6\47\1\116\1\0\54\47\1\0"+
    "\2\41\1\3\13\0\1\41\1\135\16\41\11\0\14\41"+
    "\1\0\2\41\1\3\13\0\20\41\11\0\3\41\1\136"+
    "\10\41\1\0\2\41\1\3\13\0\20\41\11\0\7\41"+
    "\1\137\4\41\1\0\2\41\1\3\13\0\1\140\17\41"+
    "\11\0\14\41\1\0\2\41\1\3\13\0\1\41\1\141"+
    "\16\41\11\0\14\41\1\0\2\41\1\3\13\0\20\41"+
    "\11\0\10\41\1\142\3\41\1\0\2\41\1\3\13\0"+
    "\11\41\1\143\6\41\11\0\14\41\1\0\2\41\1\3"+
    "\13\0\20\41\11\0\1\41\1\144\12\41\1\0\2\41"+
    "\1\3\13\0\11\41\1\145\6\41\11\0\14\41\1\0"+
    "\2\41\1\3\13\0\20\41\11\0\1\41\1\146\12\41"+
    "\1\0\2\41\1\3\13\0\1\147\17\41\11\0\14\41"+
    "\1\0\2\41\1\3\13\0\20\41\11\0\10\41\1\150"+
    "\3\41\1\0\2\41\1\3\13\0\20\41\11\0\4\41"+
    "\1\151\7\41\1\0\2\41\1\3\13\0\11\41\1\152"+
    "\6\41\11\0\14\41\1\0\2\41\1\3\13\0\1\41"+
    "\1\153\16\41\11\0\14\41\1\0\2\41\1\3\13\0"+
    "\10\41\1\154\7\41\11\0\5\41\1\155\6\41\1\0"+
    "\2\41\1\3\13\0\1\41\1\156\16\41\11\0\14\41"+
    "\1\0\2\41\1\3\13\0\11\41\1\157\6\41\11\0"+
    "\14\41\1\0\2\41\1\3\13\0\20\41\11\0\5\41"+
    "\1\160\6\41\1\0\2\41\1\3\13\0\20\41\11\0"+
    "\6\41\1\161\5\41\1\0\2\41\1\3\13\0\20\41"+
    "\11\0\1\41\1\162\12\41\1\0\2\41\1\3\13\0"+
    "\20\41\11\0\4\41\1\163\7\41\1\0\2\41\1\3"+
    "\13\0\11\41\1\164\6\41\11\0\14\41\1\0\2\41"+
    "\1\3\13\0\1\41\1\165\16\41\11\0\14\41\1\0"+
    "\2\41\1\3\13\0\20\41\11\0\4\41\1\166\7\41"+
    "\1\0\2\41\1\3\13\0\1\41\1\167\16\41\11\0"+
    "\14\41\1\0\2\41\1\3\13\0\3\41\1\170\14\41"+
    "\11\0\14\41\1\0\2\41\1\3\13\0\1\41\1\171"+
    "\16\41\11\0\14\41\1\0\2\41\1\3\13\0\11\41"+
    "\1\172\6\41\11\0\14\41\1\0\2\41\1\3\13\0"+
    "\1\41\1\173\16\41\11\0\14\41\1\0\2\41\1\3"+
    "\13\0\20\41\11\0\1\174\13\41\1\0\2\41\1\3"+
    "\13\0\20\41\11\0\3\41\1\175\10\41\1\0\2\41"+
    "\1\3\13\0\1\176\17\41\11\0\14\41\1\0\2\41"+
    "\1\3\13\0\1\41\1\177\16\41\11\0\14\41\1\0"+
    "\2\41\1\3\13\0\11\41\1\200\6\41\11\0\14\41"+
    "\1\0\2\41\1\3\13\0\13\41\1\201\4\41\11\0"+
    "\14\41";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5200];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\10\1\1\11\11\1\1\11\1\1\6\11"+
    "\10\1\1\11\2\0\1\1\1\0\1\1\1\11\21\1"+
    "\1\0\20\1\1\0\1\11\62\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[129];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
    private Symbol symbol (int type, Object value){
        return new Symbol (type, yyline, yycolumn,value);
    }
 private Symbol symbol (int type){
        return new Symbol (type, yyline);
    }
    


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  LexerCup(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  LexerCup(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 37: 
          { return new Symbol(sym.func_ContCarac, yychar, yyline, yytext());
          }
        case 39: break;
        case 26: 
          { return new Symbol(sym.Flotante, yychar, yyline, yytext());
          }
        case 40: break;
        case 16: 
          { return new Symbol(sym.Llave_a, yychar, yyline, yytext());
          }
        case 41: break;
        case 4: 
          { return new Symbol(sym.Adicion, yychar, yyline, yytext());
          }
        case 42: break;
        case 21: 
          { return new Symbol(sym.ERR_NUM, yychar, yyline, yytext());
          }
        case 43: break;
        case 31: 
          { return new Symbol(sym.Selector, yychar, yyline, yytext());
          }
        case 44: break;
        case 18: 
          { return new Symbol(sym.Corchete_a, yychar, yyline, yytext());
          }
        case 45: break;
        case 34: 
          { return new Symbol(sym.CicloFor, yychar, yyline, yytext());
          }
        case 46: break;
        case 36: 
          { return new Symbol(sym.func_Imprimir, yychar, yyline, yytext());
          }
        case 47: break;
        case 38: 
          { return new Symbol(sym.CicloMientras, yychar, yyline, yytext());
          }
        case 48: break;
        case 24: 
          { return new Symbol(sym.Si, yychar, yyline, yytext());
          }
        case 49: break;
        case 7: 
          { return new Symbol(sym.Cociente, yychar, yyline, yytext());
          }
        case 50: break;
        case 8: 
          { return new Symbol(sym.Comillas, yychar, yyline, yytext());
          }
        case 51: break;
        case 14: 
          { return new Symbol(sym.Parentesis_a, yychar, yyline, yytext());
          }
        case 52: break;
        case 20: 
          { return new Symbol(sym.ERR_ID, yychar, yyline, yytext());
          }
        case 53: break;
        case 28: 
          { return new Symbol(sym.Caso, yychar, yyline, yytext());
          }
        case 54: break;
        case 13: 
          { return new Symbol(sym.Sustraccion, yychar, yyline, yytext());
          }
        case 55: break;
        case 32: 
          { return new Symbol(sym.VarCar, yychar, yyline, yytext());
          }
        case 56: break;
        case 17: 
          { return new Symbol(sym.Llave_c, yychar, yyline, yytext());
          }
        case 57: break;
        case 12: 
          { return new Symbol(sym.Punto_Coma, yychar, yyline, yytext());
          }
        case 58: break;
        case 33: 
          { return new Symbol(sym.func_ValCad, yychar, yyline, yytext());
          }
        case 59: break;
        case 19: 
          { return new Symbol(sym.Corchete_c, yychar, yyline, yytext());
          }
        case 60: break;
        case 9: 
          { return new Symbol(sym.Op_Logico, yychar, yyline, yytext());
          }
        case 61: break;
        case 30: 
          { return new Symbol(sym.Entero, yychar, yyline, yytext());
          }
        case 62: break;
        case 3: 
          { return new Symbol(sym.Num_Entero, yychar, yyline, yytext());
          }
        case 63: break;
        case 15: 
          { return new Symbol(sym.Parentesis_c, yychar, yyline, yytext());
          }
        case 64: break;
        case 10: 
          { return new Symbol(sym.Op_Relacional, yychar, yyline, yytext());
          }
        case 65: break;
        case 29: 
          { return new Symbol(sym.func_Long, yychar, yyline, yytext());
          }
        case 66: break;
        case 11: 
          { return new Symbol(sym.Asignacion, yychar, yyline, yytext());
          }
        case 67: break;
        case 1: 
          { return new Symbol(sym.ERROR, yychar, yyline, yytext());
          }
        case 68: break;
        case 22: 
          { return new Symbol(sym.Op_Atribucion, yychar, yyline, yytext());
          }
        case 69: break;
        case 25: 
          { return new Symbol(sym.Op_Booleano, yychar, yyline, yytext());
          }
        case 70: break;
        case 5: 
          { /*Ignore*/
          }
        case 71: break;
        case 35: 
          { return new Symbol(sym.Declarar, yychar, yyline, yytext());
          }
        case 72: break;
        case 2: 
          { return new Symbol(sym.Identificador, yychar, yyline, yytext());
          }
        case 73: break;
        case 6: 
          { return new Symbol(sym.Producto, yychar, yyline, yytext());
          }
        case 74: break;
        case 23: 
          { return new Symbol(sym.Texto, yychar, yyline, yytext());
          }
        case 75: break;
        case 27: 
          { return new Symbol(sym.Sino, yychar, yyline, yytext());
          }
        case 76: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
