
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20150930 (SVN rev 66)
//----------------------------------------------------

package Ventanas;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int Producto = 16;
  public static final int VarCar = 3;
  public static final int Entero = 2;
  public static final int Llave_c = 21;
  public static final int CicloFor = 11;
  public static final int Llave_a = 20;
  public static final int Adicion = 14;
  public static final int Op_Logico = 26;
  public static final int func_Imprimir = 36;
  public static final int ERR_ID = 38;
  public static final int Asignacion = 30;
  public static final int Corchete_c = 23;
  public static final int Corchete_a = 22;
  public static final int Campotrabajo = 13;
  public static final int CicloMientras = 10;
  public static final int Op_Relacional = 27;
  public static final int func_ValCad = 35;
  public static final int Flotante = 4;
  public static final int Parentesis_c = 19;
  public static final int ERR_NUM = 39;
  public static final int Parentesis_a = 18;
  public static final int EOF = 0;
  public static final int error = 1;
  public static final int Texto = 5;
  public static final int Op_Booleano = 28;
  public static final int Caso = 9;
  public static final int func_ContCarac = 34;
  public static final int Selector = 8;
  public static final int ERROR = 37;
  public static final int Cociente = 17;
  public static final int Punto_Coma = 24;
  public static final int Identificador = 32;
  public static final int Si = 6;
  public static final int func_Ver = 33;
  public static final int Sino = 7;
  public static final int Declarar = 12;
  public static final int Num_Entero = 31;
  public static final int Sustraccion = 15;
  public static final int Op_Atribucion = 29;
  public static final int Comillas = 25;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "Entero",
  "VarCar",
  "Flotante",
  "Texto",
  "Si",
  "Sino",
  "Selector",
  "Caso",
  "CicloMientras",
  "CicloFor",
  "Declarar",
  "Campotrabajo",
  "Adicion",
  "Sustraccion",
  "Producto",
  "Cociente",
  "Parentesis_a",
  "Parentesis_c",
  "Llave_a",
  "Llave_c",
  "Corchete_a",
  "Corchete_c",
  "Punto_Coma",
  "Comillas",
  "Op_Logico",
  "Op_Relacional",
  "Op_Booleano",
  "Op_Atribucion",
  "Asignacion",
  "Num_Entero",
  "Identificador",
  "func_Ver",
  "func_ContCarac",
  "func_ValCad",
  "func_Imprimir",
  "ERROR",
  "ERR_ID",
  "ERR_NUM"
  };
}

